// Phase 5 — API layer public surface.
export { getApiBaseUrl } from './config';
export { ApiClient, ApiError, apiErrorMessage, isRevisionConflict } from './client';
export type { ApiClientOptions, HttpMethod, RequestOptions, ResponseWithHeaders } from './client';
export { getMe, login, logout, refreshTokens, register } from './auth';
export { createPlaybackSession, reportPlayEvent } from './playback';
export {
  getMyEntitlement,
  getMySubscription,
  getStoreProducts,
  verifyPurchase,
} from './subscriptions';
export { getAudioStatus, retryTrackAudio, uploadTrackAudio } from './ingestion';
export type { AudioStatus, UploadableAudio } from './ingestion';
export {
  getArtistAlbumStats,
  getArtistOverview,
  getArtistRecentActivity,
  getArtistTrackStats,
  getArtistTrend,
  getPlatformOverview,
} from './analytics';
export * from './royalties';
export type {
  AlbumAnalytics,
  AnalyticsOverview,
  AnalyticsRange,
  AnalyticsTotals,
  AnalyticsTrend,
  RecentPlay,
  TrackAnalytics,
  TrendGranularity,
  TrendPoint,
} from './types';
export type {
  AnalyticsPagedQuery,
  AnalyticsQuery,
  AnalyticsRecentQuery,
  AnalyticsTrendQuery,
} from './analytics';
export {
  createAlbum,
  createArtist,
  createTrack,
  deleteAlbum,
  deleteArtist,
  deleteTrack,
  listMyArtists,
  updateAlbum,
  updateArtist,
  updateArtistProfile,
  updateTrack,
} from './artist';
export type {
  CreateAlbumInput,
  CreateArtistInput,
  CreateTrackInput,
  UpdateAlbumInput,
  UpdateArtistInput,
  UpdateArtistProfileInput,
  UpdateTrackInput,
} from './artist';
export {
  getAlbum,
  getArtist,
  getGenre,
  getPlaylist,
  listAlbums,
  listArtists,
  listGenres,
  listPublicPlaylists,
  listTracks,
} from './catalog';
export type { AlbumListQuery, ArtistListQuery, ListQuery, TrackListQuery } from './catalog';
export {
  addTrackToPlaylist,
  createPlaylist,
  deletePlaylist,
  followArtist,
  likeTrack,
  listFollowedArtists,
  listHistory,
  listLikedTracks,
  listMyPlaylists,
  movePlaylistItem,
  removePlaylistItem,
  unfollowArtist,
  unlikeTrack,
  updatePlaylist,
} from './library';
export {
  PLAYLIST_REVISION_HEADER,
  acceptInvitation,
  addTrackCollaborative,
  createInvitation,
  leavePlaylist,
  listInvitations,
  listMembers,
  listPlaylistChanges,
  movePlaylistItemCollaborative,
  removeMember,
  removePlaylistItemCollaborative,
  revokeInvitation,
  setCollaborationEnabled,
} from './collab';
export type { CollaborativeMutation, RevisionedResult } from './collab';
export {
  addReaction,
  createComment,
  createPost,
  deleteComment,
  deletePost,
  getPost,
  listArtistPosts,
  listComments,
  listCommunityFeed,
  removeReaction,
  reportCommunityContent,
  updatePost,
} from './community';
export type {
  ArtistPost,
  CommunityAuthor,
  CommunityContentStatus,
  CommunityQuery,
  CreatePostInput,
  ModerationReport,
  PostAlbumRef,
  PostArtistRef,
  PostComment,
  PostTrackRef,
  ReactionResult,
  ReportCommunityInput,
  UpdatePostInput,
} from './community';
export {
  createRoom,
  createRoomInvitation,
  endRoom,
  getRoomState,
  joinRoom,
  leaveRoom,
  listRoomInvitations,
  listRoomMembers,
  revokeRoomInvitation,
} from './rooms';
export type {
  CreateRoomInput,
  CreateRoomInvitationResult,
  RoomInvitation,
  RoomMember,
  RoomPlaybackState,
  RoomRole,
  RoomState,
  RoomStatus,
  RoomTrack,
} from './rooms';
export type {
  AddTrackInput,
  AlbumDetail,
  AlbumListItem,
  AlbumTrack,
  AlbumType,
  ArtistDetail,
  ArtistListItem,
  ArtistProfile,
  ArtistSummary,
  AuthResult,
  AudioIngestStatus,
  CollaborationSettings,
  CollaboratorRole,
  CreateInvitationResult,
  CreatePlaylistInput,
  FieldError,
  FollowItem,
  Genre,
  HistoryItem,
  LikeItem,
  LoginInput,
  Page,
  PageInfo,
  PlaybackSession,
  PlayEventType,
  PlaylistChange,
  PlaylistChangeAction,
  PlaylistDetail,
  PlaylistInvitation,
  PlaylistItem,
  PlaylistListItem,
  PlaylistMember,
  PlaylistVisibility,
  ProblemDetail,
  RegisterInput,
  Subscription,
  SubscriptionPlan,
  SubscriptionProvider,
  SubscriptionStatus,
  Entitlement,
  MySubscription,
  StoreProduct,
  StoreProductsResponse,
  VerifyPurchaseResponse,
  TokenPair,
  TrackDetail,
  TrackGenreRef,
  TrackListItem,
  TrackStatus,
  TrackSummary,
  UpdatePlaylistInput,
  User,
  UserRole,
  ViewerRole,
} from './types';
