// Phase 5 — API layer public surface.
export { getApiBaseUrl } from './config';
export { ApiClient, ApiError, apiErrorMessage } from './client';
export type { ApiClientOptions, HttpMethod, RequestOptions } from './client';
export { getMe, login, logout, refreshTokens, register } from './auth';
export { createPlaybackSession, reportPlayEvent } from './playback';
export {
  getAlbum,
  getArtist,
  getGenre,
  getPlaylist,
  listAlbums,
  listArtists,
  listGenres,
  listPublicPlaylists,
  listTracks,
} from './catalog';
export type { AlbumListQuery, ArtistListQuery, ListQuery, TrackListQuery } from './catalog';
export {
  addTrackToPlaylist,
  createPlaylist,
  deletePlaylist,
  followArtist,
  likeTrack,
  listFollowedArtists,
  listHistory,
  listLikedTracks,
  listMyPlaylists,
  movePlaylistItem,
  removePlaylistItem,
  unfollowArtist,
  unlikeTrack,
  updatePlaylist,
} from './library';
export type {
  AddTrackInput,
  AlbumDetail,
  AlbumListItem,
  AlbumTrack,
  AlbumType,
  ArtistDetail,
  ArtistListItem,
  ArtistProfile,
  ArtistSummary,
  AuthResult,
  CreatePlaylistInput,
  FieldError,
  FollowItem,
  Genre,
  HistoryItem,
  LikeItem,
  LoginInput,
  Page,
  PageInfo,
  PlaybackSession,
  PlayEventType,
  PlaylistDetail,
  PlaylistItem,
  PlaylistListItem,
  PlaylistVisibility,
  ProblemDetail,
  RegisterInput,
  TokenPair,
  TrackDetail,
  TrackGenreRef,
  TrackListItem,
  TrackStatus,
  TrackSummary,
  UpdatePlaylistInput,
  User,
  UserRole,
} from './types';
